[package]
name = "wamex_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
base16 = "0.2.1"
digest = "0.10.7"
quote = "1.0.36"
sha2 = "0.10.8"
syn = "2.0.59"
proc-macro2 = { version = "1.0.103", features = ["span-locations"] }
[lib]
proc-macro = true


[package.metadata.docs.rs]
rustdocflags = ["--document-private-items"]
