//! Representation of metadata about wasm modules, their dependencies and versions.
//! `wamex-cli` generates this metadata during splitting if `--metadata` flag is passed.
//! `wamex_link` uses this metadata to resolve dependencies and load modules.
//!
//!

use std::fmt::Display;

pub mod dylink0;

/// Unique identifier of content.
/// This is generated by `split` command and used to distinguish different versions of the same content.
#[derive(Default, Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash)]
pub struct BumpVersion {
    pub version: u32,
}
impl BumpVersion {
    pub fn new() -> Self {
        BumpVersion { version: 0 }
    }
    pub fn from_bytes(arr: &[u8; 4]) -> Self {
        BumpVersion {
            version: u32::from_le_bytes(*arr),
        }
    }
    pub fn encode(&self) -> [u8; 4] {
        self.version.to_le_bytes()
    }

    pub fn bump(&mut self) {
        self.version += 1;
    }
}

impl Display for BumpVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "v{}", self.version)
    }
}

#[derive(Debug, PartialEq, PartialOrd, Eq, Ord, Hash, Clone)]
pub struct ModuleId {
    name: String,
    version: Option<BumpVersion>,
    module_url_path: Option<String>,
}

impl ModuleId {
    pub fn new(name: &str) -> Self {
        ModuleId {
            name: name.to_string(),
            version: None,
            module_url_path: None,
        }
    }
    pub fn dep_from_module(module: &ModuleId, dep_name: &str) -> Self {
        ModuleId {
            name: dep_name.to_string(),
            version: None,
            module_url_path: module.module_url_path.clone(),
        }
    }
    pub fn new_with_url(name: &str, module_url_path: &str) -> Self {
        ModuleId {
            name: name.to_string(),
            version: None,
            module_url_path: Some(module_url_path.to_string()),
        }
    }
    pub fn new_from_components(
        name: String,
        version: Option<BumpVersion>,
        module_url_path: Option<String>,
    ) -> Self {
        ModuleId {
            name,
            version,
            module_url_path,
        }
    }

    pub fn set_url_path(&mut self, url_path: &str) {
        self.module_url_path = Some(url_path.to_string());
    }
    pub fn module_name(&self) -> &str {
        &self.name
    }

    /// Return full module name including version if any.
    pub fn module_full_name(&self) -> String {
        let version = if let Some(version) = &self.version {
            format!("-{}", version)
        } else {
            String::new()
        };
        format!("{}{}", self.name, version)
    }

    pub fn download_url(&self) -> String {
        let url = if let Some(url) = &self.module_url_path {
            format!("{}/", url)
        } else {
            String::new()
        };
        let version = if let Some(version) = &self.version {
            format!("-{}", version)
        } else {
            String::new()
        };

        let name = &self.name;
        format!("{}/{}{}.wasm", url, name, version)
    }
}
