//! Representation of metadata about wasm modules, their dependencies and versions.
//! `wamex-cli` generates this metadata during splitting if `--metadata` flag is passed.
//! `wamex_link` uses this metadata to resolve dependencies and load modules.
//!
//!

use std::{collections::BTreeMap, hash::Hasher};

use bitcode::{Decode, Encode};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};
#[cfg(feature = "serde")]
mod from_str;
/// Unique identifier of content.
/// This is generated by `split` command and used to distinguish different versions of the same content.
#[derive(Default, Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Decode, Encode)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct BumpVersion {
    pub version: u32,
}
impl BumpVersion {
    pub fn new() -> Self {
        BumpVersion { version: 0 }
    }

    pub fn bump(&mut self) {
        self.version += 1;
    }
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Decode, Encode)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "snake_case"))]
pub enum Type {
    I32,
    I64,
    F32,
    F64,
    V128,
    FuncRef,
    ExternRef,
    // Add other types as needed
    // Like structs, arrays, etc.
}

#[derive(Debug, Clone, PartialOrd, Ord, Eq, Decode, Encode)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct DemangledName {
    pub name: String,
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "String::is_empty"))]
    pub distinguishing_hash: String,
    pub anonymous: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Decode, Encode)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", rename_all = "snake_case"))]
pub enum SymbolSignature {
    Function {
        name: DemangledName,
        // If lazy is true the module should be loaded before calling the function.
        // This also means that it cannot be directly "imported" by other modules.
        #[cfg_attr(feature = "serde", serde(skip_serializing_if = "std::ops::Not::not"))]
        lazy: bool,
        #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Vec::is_empty"))]
        params: Vec<Type>,
        #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Vec::is_empty"))]
        results: Vec<Type>,
    },
    Data {
        name: DemangledName,
        // TODO: offset?
        size: u32,
    },
}

impl SymbolSignature {
    /// Display implementation, but currently due to unstable implementation kept as a separate function.
    #[cfg(feature = "serde")]
    pub fn display_signature(&self) -> String {
        match self {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                let mut result = String::new();
                if *lazy {
                    result.push_str("lazy ");
                }
                result.push_str("fn");
                name.validate_name_spec_symbols()
                    .expect("Function name contains invalid characters for display");
                result.push_str(&format!(" {}(", name.name));
                for (i, param) in params.iter().enumerate() {
                    if i > 0 {
                        result.push_str(", ");
                    }
                    result.push_str(&format!("{param:?}"));
                }
                result.push_str(")");
                if !results.is_empty() {
                    result.push_str(" -> ");
                    for (i, result_type) in results.iter().enumerate() {
                        if i > 0 {
                            result.push_str(", ");
                        }
                        result.push_str(&format!("{result_type:?}"));
                    }
                }
                result
            }
            SymbolSignature::Data { size, name } => {
                name.validate_name_spec_symbols()
                    .expect("Data name contains invalid characters for display");
                format!("data ({}):{}", name.name, size)
            }
        }
    }
}

#[derive(Default, Debug, Clone, PartialEq, Eq, Hash, Decode, Encode)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Module {
    pub version: BumpVersion,
    pub provides: Vec<ExportedSymbol>,
    pub deps: BTreeMap<String, Vec<ExportedSymbol>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Decode, Encode)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct ExportedSymbol {
    pub version: BumpVersion,
    #[cfg_attr(feature = "serde", serde(flatten))]
    pub signature: SymbolSignature,
}

impl DemangledName {
    // Only data can be annonymous
    pub fn new(name: &str, can_be_anonymous: bool) -> Self {
        if can_be_anonymous && Self::is_name_anonymous(name) {
            return DemangledName {
                name: name.to_string(),
                distinguishing_hash: String::new(),
                anonymous: true,
            };
        }
        let (name, distinguishing_hash) = Self::demangle_name(name);

        DemangledName {
            name,
            distinguishing_hash,
            anonymous: false,
        }
    }

    #[cfg(feature = "parser")]
    fn demangle_name(name: &str) -> (String, String) {
        let name = rustc_demangle::demangle(name);
        let full = name.to_string();
        let start = format!("{:#}", name);
        let suffix = full
            .strip_prefix(&start)
            .and_then(|s| s.strip_prefix("::h"))
            .map_or_else(String::new, |s| s.to_string());

        (start, suffix)
    }

    #[cfg(not(feature = "parser"))]
    fn demangle_name(name: &str) -> (String, String) {
        (name.to_string(), String::new())
    }

    pub(crate) fn is_name_anonymous(name: &str) -> bool {
        // .Lanon used by llvm, but any prefixed with ".L" can be considered anonymous.
        // TODO: refine better criteria for anonymous symbols.
        name.starts_with(".L")
    }

    /// Check if name contains blacklisted characters that would interfere with parsing
    fn validate_name_spec_symbols(&self) -> Result<(), String> {
        let mut angle_bracket_depth = 0;
        let mut chars = self.name.chars();

        while let Some(ch) = chars.next() {
            match ch {
                '<' => angle_bracket_depth += 1,
                '>' => {
                    if angle_bracket_depth > 0 {
                        angle_bracket_depth -= 1;
                    } else {
                        return Err(format!(
                            "Name '{}' contains unmatched '>' character",
                            self.name
                        ));
                    }
                }
                '(' | ')' => {
                    if angle_bracket_depth == 0 {
                        return Err(format!(
                            "Name '{}' contains '{}' outside of angle brackets",
                            self.name, ch
                        ));
                    }
                }
                _ => {}
            }
        }

        // Check for unmatched angle brackets
        if angle_bracket_depth > 0 {
            return Err(format!(
                "Name '{}' contains unmatched '<' character(s)",
                self.name
            ));
        }

        Ok(())
    }
}

impl std::hash::Hash for DemangledName {
    fn hash<H: Hasher>(&self, state: &mut H) {
        // For anonymous symbols name is only used for debugging purposes.
        if self.anonymous {
            return;
        }
        state.write(self.name.as_bytes());
        state.write(self.distinguishing_hash.as_bytes());
    }
}

impl PartialEq for DemangledName {
    fn eq(&self, other: &Self) -> bool {
        if self.anonymous && other.anonymous {
            return true;
        }
        self.name == other.name
    }
}

#[cfg(feature = "parser")]
impl TryFrom<&wasmparser::ValType> for Type {
    type Error = &'static str;

    fn try_from(val_type: &wasmparser::ValType) -> Result<Self, Self::Error> {
        match val_type {
            wasmparser::ValType::I32 => Ok(Type::I32),
            wasmparser::ValType::I64 => Ok(Type::I64),
            wasmparser::ValType::F32 => Ok(Type::F32),
            wasmparser::ValType::F64 => Ok(Type::F64),
            wasmparser::ValType::V128 => Ok(Type::V128),
            wasmparser::ValType::Ref(r) if r.is_extern_ref() => Ok(Type::ExternRef),
            wasmparser::ValType::Ref(r) if r.is_func_ref() => Ok(Type::FuncRef),
            _ => Err("Unsupported ValType for conversion to Type"),
        }
    }
}
