[package]
name = "wamex_object"
version = "0.1.0"
edition = "2024"
license-file = "../../LICENSE"
description = "WASM object reader + emitter for wamex"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
hex = "0.4.3"
leb128fmt = "0.1.0"
log = "0.4.20"
rustc-demangle = "0.1.21"
smallvec = { version = "1.15", features = ["write"] }
vec_map = "0.8.2"
wasm-encoder = { version = "0.238.0", features = ["wasmparser"] }
wasmparser = "0.238.0"
wamex_types = { version = "0.1.0", path = "../wamex_types", features = [
    "full",
] }
cranelift-entity = "0.126.1"
cranelift-bitset = "0.126.1"
fnv = "1.0.7"
pub_if = "0.1"
nom = { version = "8.0.0", features = ["std"] }
derive_more = { version = "2.1.1", features = ["display", "debug", "from"] }
itertools = "0.14"
yoke = { version = "0.8", features = ["derive"] }
tracing = "0.1"

[dev-dependencies]
tempdir = "0.3"
insta = "1.43"
env_logger = "0.11.0"
criterion = { version = "0.8", features = ["html_reports"] }
profiler = { version = "0.1.0", path = "../../../profiler" }


[features]
default = []
unstable = [] # enable unstable APIs

[[bench]]
name = "split_benchmarks"
harness = false


[[bench]]
name = "multi_phase"
harness = false
