[package]
name = "wamex_object"
version = "0.1.0"
edition = "2024"
license-file = "../../LICENSE"
description = "WASM object reader + emitter for wamex"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
hex = "0.4.3"
leb128fmt = "0.1.0"
log = "0.4.20"
rustc-demangle = "0.1.21"
smallvec = "1.15"
vec_map = "0.8.2"
wasm-encoder = { version = "0.238.0", features = ["wasmparser"] }
wasmparser = "0.238.0"
wamex_types = { version = "0.1.0", path = "../wamex_types", features = ["full"] }

