[package]
name = "wamex_example"
version = "0.1.0"
authors = ["Volodymyr Motylenko <me@vldm.cc>"]
edition = "2021"
license-file = "../../LICENSE"
description = "An example WebAssembly binary splitted with wamex"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.82"
async-compression = { version = "0.4.8", features = ["futures-io"] }
futures = "0.3.30"
js-sys = "0.3.69"
wasm-bindgen = "^0.2.104"
wasm-bindgen-futures = "0.4.42"
wasm-streams = "0.4.0"
wamex = { version = "0.1.0", path = "../wamex", optional = true }
wasm-log = "0.3"
hex = "0.4"

[features]
default = ["split"]
split = ["dep:wamex"]
gzip = ["async-compression/gzip"]
brotli = ["async-compression/brotli"]
