[package]
name = "wamex-cli"
version = "0.1.0"
edition = "2024"
authors = ["Volodymyr Motylenko <me@vldm.cc>"]
license-file = "../../LICENSE"
description = "Command line interface for wamex splitter"


[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
clap = { version = "4.5.4", features = ["derive"] }

wasm-encoder = { version = "0.238.0", features = ["wasmparser"] }
wasmparser = "0.238.0"
vec_map = "0.8.2"
log = "0.4.20"
env_logger = "0.11.0"
leb128fmt = "0.1.0"
nom = { version = "8.0.0", features = ["std"] }
hex = "0.4.3"
similar = { version = "2", features = ["inline"] }
colored = "3"
derivative = "2.2"
smallvec = "1.15"
ptree = "0.5.0"
linear-map = "1.2.0"

wamex_types = { version = "0.1.0", path = "../wamex_types", optional = true, features = [
    "full",
] }
rustc-demangle = "0.1.21"

[dev-dependencies]
tempdir = "0.3"
insta = "1.43"
criterion = { version = "0.5", features = ["html_reports"] }
lazy_static = "1.4.0"

[features]
default = ["metadata"]
metadata = ["dep:wamex_types"]

[[bench]]
name = "split_benchmarks"
harness = false
