# Flags for cli
[target.x86_64-unknown-linux-gnu]
rustflags = ['-Ctarget-cpu=native'] # for gxhash

# Flags for examples
[target.wasm32-unknown-unknown]
rustflags = ['-Clink-args=--emit-relocs']

# [unstable]
# codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"