[package]
name = "wamex_link"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Request", "Response", "Window"] }
js-sys = "0.3"

thiserror = "2.0"
wamex_metadata = { version = "0.1.0", path = "../wamex_metadata", features = [
    "parser",
] }
wasmparser = "0.238.0"

# Under debug feature
log = { version = "0.4", optional = true }


[features]
default = ["rkyv", "debug"]
debug = ["dep:log"]
rkyv = ["wamex_metadata/rkyv"]
