//! This module contains serialization and deserialization of the metadata
//! that is used by wasm-split to store information about resulting modules and linkage between them.
//!
//! This metadata is used for linker to determine if module compatible with other modules.
//!
//!

use std::{collections::BTreeMap, fmt::Debug, hash::Hasher};

use anyhow::Result;
use serde::{Deserialize, Serialize};
use wasmparser::ValType;

use crate::{
    analysis::{
        dep_graph::DepNode,
        split_point::{SplitModuleIdentifier, SplitProgramInfo},
        ModuleInfo,
    },
    helpers::demangle_name,
    index::{DataSegmentId, DataSymbolId, InputFuncId},
    ModuleStructure,
};

/// Unique identifier of content.
/// This is generated by `split` command and used to distinguish different versions of the same content.
#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BumpVersion {
    version: u32,
}
impl BumpVersion {
    pub fn new() -> Self {
        BumpVersion { version: 0 }
    }

    pub fn bump(&mut self) {
        self.version += 1;
    }
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Type {
    I32,
    I64,
    F32,
    F64,
    V128,
    FuncRef,
    ExternRef,
    // Add other types as needed
    // Like structs, arrays, etc.
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Serialize, Deserialize)]
pub struct DemangledName {
    pub name: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    pub distinguishing_hash: String,
    pub anonymous: bool,
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SymbolSignature {
    Function {
        name: DemangledName,
        // If lazy is true the module should be loaded before calling the function.
        // This also means that it cannot be directly "imported" by other modules.
        #[serde(skip_serializing_if = "std::ops::Not::not")]
        lazy: bool,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        params: Vec<Type>,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        results: Vec<Type>,
    },
    Data {
        name: DemangledName,
        size: u32,
    },
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Module {
    version: BumpVersion,
    provides: Vec<ExportedSymbol>,
    deps: BTreeMap<String, Vec<ExportedSymbol>>,
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExportedSymbol {
    version: BumpVersion,
    #[serde(flatten)]
    signature: SymbolSignature,
}

impl DemangledName {
    // Only data can be annonymous
    pub fn new(name: &str, can_be_anonymous: bool) -> Self {
        if can_be_anonymous && Self::is_anonymous(name) {
            return DemangledName {
                name: name.to_string(),
                distinguishing_hash: String::new(),
                anonymous: true,
            };
        }
        let (name, distinguishing_hash) = demangle_name(name);

        DemangledName {
            name,
            distinguishing_hash,
            anonymous: false,
        }
    }
    fn is_anonymous(name: &str) -> bool {
        // .Lanon used by llvm, but any prefixed with ".L" can be considered anonymous.
        // TODO: refine better criteria for anonymous symbols.
        name.starts_with(".L")
    }
}

impl SymbolSignature {
    pub fn from_input_function(module_info: &ModuleInfo, func_id: InputFuncId, lazy: bool) -> Self {
        let name = module_info
            .source
            .names
            .functions
            .get(func_id)
            .expect("Function name should be defined");

        let funct_type_id = module_info.get_function_type_id(func_id);

        let type_info = module_info
            .source
            .types
            .get(funct_type_id)
            .expect("Function type should be defined");
        let params = type_info
            .params()
            .into_iter()
            .map(Type::try_from)
            .collect::<Result<Vec<_>, _>>()
            .expect("Failed to convert function parameter types");
        let results = type_info
            .results()
            .into_iter()
            .map(Type::try_from)
            .collect::<Result<Vec<_>, _>>()
            .expect("Failed to convert function result types");

        SymbolSignature::Function {
            name: DemangledName::new(name, false),
            lazy,
            params,  // Populate with actual parameter types if available
            results, // Populate with actual result type if available
        }
    }

    pub fn from_data_symbol(
        module_info: &ModuleInfo,
        segment: DataSegmentId,
        idx: DataSymbolId,
    ) -> Self {
        let symbol = module_info
            .source
            .linking
            .get_data_in_segment(segment, idx)
            .expect("Data symbol should be defined");

        SymbolSignature::Data {
            size: symbol.size,
            name: DemangledName::new(symbol.name, true),
        }
    }

    pub fn from_node(module_info: &ModuleInfo, node: &crate::analysis::dep_graph::DepNode) -> Self {
        match node {
            crate::analysis::dep_graph::DepNode::Function(func_id) => {
                Self::from_input_function(module_info, *func_id, false)
            }
            crate::analysis::dep_graph::DepNode::DataSymbol(segment, idx) => {
                Self::from_data_symbol(module_info, *segment, *idx)
            }
        }
    }

    pub fn display_signature(&self) -> String {
        match self {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                let mut result = String::new();
                if *lazy {
                    result.push_str("lazy ");
                }
                result.push_str("fn");
                result.push_str(&format!(" {name}(", name = name.name));
                for (i, param) in params.iter().enumerate() {
                    if i > 0 {
                        result.push_str(", ");
                    }
                    result.push_str(&format!("{param:?}"));
                }
                result.push_str(")");
                if !results.is_empty() {
                    result.push_str(" -> ");
                    for (i, result_type) in results.iter().enumerate() {
                        if i > 0 {
                            result.push_str(", ");
                        }
                        result.push_str(&format!("{result_type:?}"));
                    }
                }
                result
            }
            SymbolSignature::Data { size, name } => {
                format!("data({name}):{size}", name = name.name)
            }
        }
    }
}

impl std::hash::Hash for DemangledName {
    fn hash<H: Hasher>(&self, state: &mut H) {
        // For anonymous symbols name is only used for debugging purposes.
        if self.anonymous {
            return;
        }
        state.write(self.name.as_bytes());
        state.write(self.distinguishing_hash.as_bytes());
    }
}

impl TryFrom<&ValType> for Type {
    type Error = &'static str;

    fn try_from(val_type: &ValType) -> Result<Self, Self::Error> {
        match val_type {
            ValType::I32 => Ok(Type::I32),
            ValType::I64 => Ok(Type::I64),
            ValType::F32 => Ok(Type::F32),
            ValType::F64 => Ok(Type::F64),
            ValType::V128 => Ok(Type::V128),
            ValType::Ref(r) if r.is_extern_ref() => Ok(Type::ExternRef),
            ValType::Ref(r) if r.is_func_ref() => Ok(Type::FuncRef),
            _ => Err("Unsupported ValType for conversion to Type"),
        }
    }
}

impl Module {
    pub fn build_modules_metadata(
        module_info: &ModuleInfo,
        program_info: &SplitProgramInfo,
        module_structure: ModuleStructure,
    ) -> BTreeMap<String, Module> {
        let modules_that_exports: BTreeMap<DepNode, SplitModuleIdentifier> = program_info
            .output_modules
            .iter()
            .fold(BTreeMap::new(), |mut acc, (name, deps)| {
                if name.is_shared()
                    || (module_structure != ModuleStructure::EmitMainChunked && name.is_main())
                {
                    for dep in &deps.link_symbols {
                        let prev = acc.insert(dep.clone(), name.clone());
                        assert!(
                            prev.is_none(),
                            "Duplicate export for {dep:?} in {name:?}, previous was {prev:?}",
                        );
                    }
                }
                acc
            });

        let mut metadata = BTreeMap::new();

        for (name, split_deps) in &program_info.output_modules {
            let module_name = name.name();
            let version = BumpVersion::new();
            let mut provides = Vec::new();
            let mut deps: BTreeMap<String, Vec<ExportedSymbol>> = BTreeMap::new();

            // Split points are exported
            for split_point in &split_deps.split_points {
                provides.push(ExportedSymbol {
                    signature: SymbolSignature::from_input_function(
                        module_info,
                        split_point.import_func,
                        true, // all split points are lazy-loading by default
                    ),
                    version: BumpVersion::new(),
                });
            }
            for node in &split_deps.link_symbols {
                let exported_symbol = ExportedSymbol {
                    signature: SymbolSignature::from_node(module_info, node),
                    version: BumpVersion::new(),
                };
                match name {
                    SplitModuleIdentifier::Shared(_) => provides.push(exported_symbol),
                    name @ SplitModuleIdentifier::Single(_)
                        if module_structure != ModuleStructure::EmitMainChunked
                            && name.is_main() =>
                    {
                        provides.push(exported_symbol);
                    }
                    SplitModuleIdentifier::Single(_) => {
                        let import_module = modules_that_exports
                            .get(node)
                            .expect("No exporting module found");
                        deps.entry(import_module.name())
                            .or_default()
                            .push(exported_symbol);
                    }
                }
            }

            metadata.insert(
                module_name,
                Module {
                    version,
                    provides,
                    deps,
                },
            );
        }

        metadata
    }
}
