//! This module contains serialization and deserialization of the metadata
//! that is used by wasm-split to store information about resulting modules and linkage between them.
//!
//! This metadata is used for linker to determine if module compatible with other modules.
//!
//!

use std::{collections::BTreeMap, fmt::Debug, hash::Hasher, str::FromStr};

use anyhow::Result;
use nom::{
    branch::alt,
    bytes::complete::{tag, take_until, take_while1},
    character::complete::{char, digit1, multispace0, multispace1},
    combinator::{map, map_res, opt},
    multi::separated_list0,
    sequence::{preceded, terminated},
    IResult,
};
use serde::{Deserialize, Serialize};
use wasmparser::ValType;

use crate::{
    analysis::{
        dep_graph::DepNode,
        split_point::{SplitModuleIdentifier, SplitProgramInfo},
        ModuleInfo,
    },
    helpers::demangle_name,
    index::{DataSegmentId, DataSymbolId, InputFuncId},
    ModuleStructure,
};

/// Unique identifier of content.
/// This is generated by `split` command and used to distinguish different versions of the same content.
#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BumpVersion {
    version: u32,
}
impl BumpVersion {
    pub fn new() -> Self {
        BumpVersion { version: 0 }
    }

    pub fn bump(&mut self) {
        self.version += 1;
    }
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Type {
    I32,
    I64,
    F32,
    F64,
    V128,
    FuncRef,
    ExternRef,
    // Add other types as needed
    // Like structs, arrays, etc.
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Serialize, Deserialize)]
pub struct DemangledName {
    pub name: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    pub distinguishing_hash: String,
    pub anonymous: bool,
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SymbolSignature {
    Function {
        name: DemangledName,
        // If lazy is true the module should be loaded before calling the function.
        // This also means that it cannot be directly "imported" by other modules.
        #[serde(skip_serializing_if = "std::ops::Not::not")]
        lazy: bool,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        params: Vec<Type>,
        #[serde(skip_serializing_if = "Vec::is_empty")]
        results: Vec<Type>,
    },
    Data {
        name: DemangledName,
        // TODO: offset?
        size: u32,
    },
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Module {
    version: BumpVersion,
    provides: Vec<ExportedSymbol>,
    deps: BTreeMap<String, Vec<ExportedSymbol>>,
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExportedSymbol {
    version: BumpVersion,
    #[serde(flatten)]
    signature: SymbolSignature,
}

impl DemangledName {
    // Only data can be annonymous
    pub fn new(name: &str, can_be_anonymous: bool) -> Self {
        if can_be_anonymous && Self::is_anonymous(name) {
            return DemangledName {
                name: name.to_string(),
                distinguishing_hash: String::new(),
                anonymous: true,
            };
        }
        let (name, distinguishing_hash) = demangle_name(name);

        DemangledName {
            name,
            distinguishing_hash,
            anonymous: false,
        }
    }

    fn is_anonymous(name: &str) -> bool {
        // .Lanon used by llvm, but any prefixed with ".L" can be considered anonymous.
        // TODO: refine better criteria for anonymous symbols.
        name.starts_with(".L")
    }

    /// Check if name contains blacklisted characters that would interfere with parsing
    fn validate_for_display(&self) -> Result<String, String> {
        const BLACKLISTED_CHARS: &[char] = &['(', ')', '<', '>', ' '];

        // Check main name for blacklisted characters
        if let Some(bad_char) = self.name.chars().find(|c| BLACKLISTED_CHARS.contains(c)) {
            return Err(format!(
                "Name '{}' contains invalid character '{}'",
                self.name, bad_char
            ));
        }

        // Only return the main name, distinguishing hash is for debugging purposes only
        Ok(self.name.clone())
    }
}

impl SymbolSignature {
    pub fn from_input_function(module_info: &ModuleInfo, func_id: InputFuncId, lazy: bool) -> Self {
        let name = module_info
            .source
            .names
            .functions
            .get(func_id)
            .expect("Function name should be defined");

        let funct_type_id = module_info.get_function_type_id(func_id);

        let type_info = module_info
            .source
            .types
            .get(funct_type_id)
            .expect("Function type should be defined");
        let params = type_info
            .params()
            .into_iter()
            .map(Type::try_from)
            .collect::<Result<Vec<_>, _>>()
            .expect("Failed to convert function parameter types");
        let results = type_info
            .results()
            .into_iter()
            .map(Type::try_from)
            .collect::<Result<Vec<_>, _>>()
            .expect("Failed to convert function result types");

        SymbolSignature::Function {
            name: DemangledName::new(name, false),
            lazy,
            params,  // Populate with actual parameter types if available
            results, // Populate with actual result type if available
        }
    }

    pub fn from_data_symbol(
        module_info: &ModuleInfo,
        segment: DataSegmentId,
        idx: DataSymbolId,
    ) -> Self {
        let symbol = module_info
            .source
            .linking
            .get_data_in_segment(segment, idx)
            .expect("Data symbol should be defined");

        SymbolSignature::Data {
            size: symbol.size,
            name: DemangledName::new(symbol.name, true),
        }
    }

    pub fn from_node(module_info: &ModuleInfo, node: &crate::analysis::dep_graph::DepNode) -> Self {
        match node {
            crate::analysis::dep_graph::DepNode::Function(func_id) => {
                Self::from_input_function(module_info, *func_id, false)
            }
            crate::analysis::dep_graph::DepNode::DataSymbol(segment, idx) => {
                Self::from_data_symbol(module_info, *segment, *idx)
            }
        }
    }

    pub fn display_signature(&self) -> String {
        match self {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                let mut result = String::new();
                if *lazy {
                    result.push_str("lazy ");
                }
                result.push_str("fn");
                let sanitized_name = name
                    .validate_for_display()
                    .expect("Function name contains invalid characters for display");
                result.push_str(&format!(" {sanitized_name}("));
                for (i, param) in params.iter().enumerate() {
                    if i > 0 {
                        result.push_str(", ");
                    }
                    result.push_str(&format!("{param:?}"));
                }
                result.push_str(")");
                if !results.is_empty() {
                    result.push_str(" -> ");
                    for (i, result_type) in results.iter().enumerate() {
                        if i > 0 {
                            result.push_str(", ");
                        }
                        result.push_str(&format!("{result_type:?}"));
                    }
                }
                result
            }
            SymbolSignature::Data { size, name } => {
                let sanitized_name = name
                    .validate_for_display()
                    .expect("Data name contains invalid characters for display");
                format!("data <{sanitized_name}>:{}", size)
            }
        }
    }
}

impl std::hash::Hash for DemangledName {
    fn hash<H: Hasher>(&self, state: &mut H) {
        // For anonymous symbols name is only used for debugging purposes.
        if self.anonymous {
            return;
        }
        state.write(self.name.as_bytes());
        state.write(self.distinguishing_hash.as_bytes());
    }
}

impl TryFrom<&ValType> for Type {
    type Error = &'static str;

    fn try_from(val_type: &ValType) -> Result<Self, Self::Error> {
        match val_type {
            ValType::I32 => Ok(Type::I32),
            ValType::I64 => Ok(Type::I64),
            ValType::F32 => Ok(Type::F32),
            ValType::F64 => Ok(Type::F64),
            ValType::V128 => Ok(Type::V128),
            ValType::Ref(r) if r.is_extern_ref() => Ok(Type::ExternRef),
            ValType::Ref(r) if r.is_func_ref() => Ok(Type::FuncRef),
            _ => Err("Unsupported ValType for conversion to Type"),
        }
    }
}

impl Module {
    pub fn build_modules_metadata(
        module_info: &ModuleInfo,
        program_info: &SplitProgramInfo,
        module_structure: ModuleStructure,
    ) -> BTreeMap<String, Module> {
        let modules_that_exports: BTreeMap<DepNode, SplitModuleIdentifier> = program_info
            .output_modules
            .iter()
            .fold(BTreeMap::new(), |mut acc, (name, deps)| {
                if name.is_shared()
                    || (module_structure != ModuleStructure::EmitMainChunked && name.is_main())
                {
                    for dep in &deps.link_symbols {
                        let prev = acc.insert(dep.clone(), name.clone());
                        assert!(
                            prev.is_none(),
                            "Duplicate export for {dep:?} in {name:?}, previous was {prev:?}",
                        );
                    }
                }
                acc
            });

        let mut metadata = BTreeMap::new();

        for (name, split_deps) in &program_info.output_modules {
            let module_name = name.name();
            let version = BumpVersion::new();
            let mut provides = Vec::new();
            let mut deps: BTreeMap<String, Vec<ExportedSymbol>> = BTreeMap::new();

            // Split points are exported
            for split_point in &split_deps.split_points {
                provides.push(ExportedSymbol {
                    signature: SymbolSignature::from_input_function(
                        module_info,
                        split_point.import_func,
                        true, // all split points are lazy-loading by default
                    ),
                    version: BumpVersion::new(),
                });
            }
            for node in &split_deps.link_symbols {
                let exported_symbol = ExportedSymbol {
                    signature: SymbolSignature::from_node(module_info, node),
                    version: BumpVersion::new(),
                };
                match name {
                    SplitModuleIdentifier::Shared(_) => provides.push(exported_symbol),
                    name @ SplitModuleIdentifier::Single(_)
                        if module_structure != ModuleStructure::EmitMainChunked
                            && name.is_main() =>
                    {
                        provides.push(exported_symbol);
                    }
                    SplitModuleIdentifier::Single(_) => {
                        let import_module = modules_that_exports
                            .get(node)
                            .expect("No exporting module found");
                        deps.entry(import_module.name())
                            .or_default()
                            .push(exported_symbol);
                    }
                }
            }

            metadata.insert(
                module_name,
                Module {
                    version,
                    provides,
                    deps,
                },
            );
        }

        metadata
    }
}

// Nom parsers for SymbolSignature
fn parse_type(input: &str) -> IResult<&str, Type> {
    use nom::Parser;
    alt((
        map(tag("I32"), |_| Type::I32),
        map(tag("I64"), |_| Type::I64),
        map(tag("F32"), |_| Type::F32),
        map(tag("F64"), |_| Type::F64),
        map(tag("V128"), |_| Type::V128),
        map(tag("FuncRef"), |_| Type::FuncRef),
        map(tag("ExternRef"), |_| Type::ExternRef),
    ))
    .parse(input)
}

fn parse_identifier(input: &str) -> IResult<&str, &str> {
    take_while1(|c: char| c.is_alphanumeric() || c == '_' || c == ':' || c == ',')(input)
}

fn parse_function_signature(input: &str) -> IResult<&str, SymbolSignature> {
    use nom::Parser;

    let (input, lazy) = opt(terminated(tag("lazy"), multispace1)).parse(input)?;
    let (input, _) = tag("fn").parse(input)?;
    let (input, _) = multispace1(input)?;
    let (input, name) = parse_identifier(input)?;
    let (input, _) = char('(')(input)?;
    let (input, params) =
        separated_list0((multispace0, char(','), multispace0), parse_type).parse(input)?;
    let (input, _) = char(')')(input)?;

    let (input, results) = opt(preceded(
        (multispace0, tag("->"), multispace0),
        separated_list0((multispace0, char(','), multispace0), parse_type),
    ))
    .parse(input)?;

    Ok((
        input,
        SymbolSignature::Function {
            name: DemangledName {
                name: name.to_string(),
                distinguishing_hash: String::new(),
                anonymous: false,
            },
            lazy: lazy.is_some(),
            params,
            results: results.unwrap_or_default(),
        },
    ))
}

fn parse_data_signature(input: &str) -> IResult<&str, SymbolSignature> {
    use nom::Parser;

    let (input, _) = tag("data").parse(input)?;
    let (input, _) = multispace1(input)?;
    let (input, _) = char('<')(input)?;
    let (input, name) = take_until(">")(input)?;
    let (input, _) = char('>')(input)?;
    let (input, _) = char(':')(input)?;
    let (input, size) = map_res(digit1, |s: &str| s.parse::<u32>()).parse(input)?;

    Ok((
        input,
        SymbolSignature::Data {
            name: DemangledName {
                name: name.to_string(),
                distinguishing_hash: String::new(),
                anonymous: false,
            },
            size,
        },
    ))
}

fn parse_symbol_signature(input: &str) -> IResult<&str, SymbolSignature> {
    use nom::Parser;
    alt((parse_function_signature, parse_data_signature)).parse(input)
}

impl FromStr for SymbolSignature {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match parse_symbol_signature(s) {
            Ok((remaining, signature)) => {
                if remaining.trim().is_empty() {
                    Ok(signature)
                } else {
                    Err(format!("Unexpected remaining input: '{}'", remaining))
                }
            }
            Err(e) => Err(format!("Parse error: {}", e)),
        }
    }
}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_display_and_parse_function_signature() {
        let signature = SymbolSignature::Function {
            name: DemangledName {
                name: "test_func".to_string(),
                distinguishing_hash: String::new(),
                anonymous: false,
            },
            lazy: false,
            params: vec![Type::I32, Type::F64],
            results: vec![Type::I32],
        };

        let display = signature.display_signature();
        assert_eq!(display, "fn test_func(I32, F64) -> I32");

        let parsed: SymbolSignature = display.parse().unwrap();
        match parsed {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                assert_eq!(name.name, "test_func");
                assert!(!lazy);
                assert_eq!(params, vec![Type::I32, Type::F64]);
                assert_eq!(results, vec![Type::I32]);
            }
            _ => panic!("Expected function signature"),
        }
    }

    #[test]
    fn test_display_and_parse_lazy_function_signature() {
        let signature = SymbolSignature::Function {
            name: DemangledName {
                name: "lazy_func".to_string(),
                distinguishing_hash: String::new(),
                anonymous: false,
            },
            lazy: true,
            params: vec![],
            results: vec![],
        };

        let display = signature.display_signature();
        assert_eq!(display, "lazy fn lazy_func()");

        let parsed: SymbolSignature = display.parse().unwrap();
        match parsed {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                assert_eq!(name.name, "lazy_func");
                assert!(lazy);
                assert!(params.is_empty());
                assert!(results.is_empty());
            }
            _ => panic!("Expected function signature"),
        }
    }

    #[test]
    fn test_display_and_parse_data_signature() {
        let signature = SymbolSignature::Data {
            name: DemangledName {
                name: "my_data".to_string(),
                distinguishing_hash: String::new(),
                anonymous: false,
            },
            size: 42,
        };

        let display = signature.display_signature();
        assert_eq!(display, "data <my_data>:42");

        let parsed: SymbolSignature = display.parse().unwrap();
        match parsed {
            SymbolSignature::Data { name, size } => {
                assert_eq!(name.name, "my_data");
                assert_eq!(size, 42);
            }
            _ => panic!("Expected data signature"),
        }
    }

    #[test]
    fn test_valid_names_with_colons_and_commas() {
        let signature = SymbolSignature::Function {
            name: DemangledName {
                name: "std::vector::push,pop".to_string(),
                distinguishing_hash: "hash:value".to_string(),
                anonymous: false,
            },
            lazy: false,
            params: vec![],
            results: vec![],
        };

        let display = signature.display_signature();
        assert_eq!(display, "fn std::vector::push,pop()");

        let parsed: SymbolSignature = display.parse().unwrap();
        match parsed {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                assert_eq!(name.name, "std::vector::push,pop");
                assert!(!lazy);
                assert!(params.is_empty());
                assert!(results.is_empty());
            }
            _ => panic!("Expected function signature"),
        }
    }

    #[test]
    fn test_invalid_name_validation() {
        let signature = SymbolSignature::Function {
            name: DemangledName {
                name: "func(with)invalid<chars>".to_string(),
                distinguishing_hash: String::new(),
                anonymous: false,
            },
            lazy: false,
            params: vec![],
            results: vec![],
        };

        // This should panic due to invalid characters
        let result = std::panic::catch_unwind(|| signature.display_signature());
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_for_display_errors() {
        let name_with_parens = DemangledName {
            name: "func(with_parens)".to_string(),
            distinguishing_hash: String::new(),
            anonymous: false,
        };
        assert!(name_with_parens.validate_for_display().is_err());

        let name_with_angle_brackets = DemangledName {
            name: "func<template>".to_string(),
            distinguishing_hash: String::new(),
            anonymous: false,
        };
        assert!(name_with_angle_brackets.validate_for_display().is_err());

        let name_with_space = DemangledName {
            name: "func with space".to_string(),
            distinguishing_hash: String::new(),
            anonymous: false,
        };
        assert!(name_with_space.validate_for_display().is_err());

        let hash_with_invalid_chars = DemangledName {
            name: "valid_name".to_string(),
            distinguishing_hash: "hash(with_parens)".to_string(),
            anonymous: false,
        };
        assert!(hash_with_invalid_chars.validate_for_display().is_err());

        // Valid cases should work
        let valid_name = DemangledName {
            name: "std::vector::push,pop".to_string(),
            distinguishing_hash: "hash:value".to_string(),
            anonymous: false,
        };
        assert!(valid_name.validate_for_display().is_ok());
    }

    #[test]
    fn test_parse_error_handling() {
        assert!("invalid signature".parse::<SymbolSignature>().is_err());
        assert!("fn incomplete(".parse::<SymbolSignature>().is_err());
        assert!("data <incomplete".parse::<SymbolSignature>().is_err());
    }

    #[test]
    fn test_distinguishing_hash_not_in_signature() {
        let signature = SymbolSignature::Function {
            name: DemangledName {
                name: "my_function".to_string(),
                distinguishing_hash: "debug_hash_info".to_string(),
                anonymous: false,
            },
            lazy: false,
            params: vec![Type::I32],
            results: vec![Type::F64],
        };

        let display = signature.display_signature();
        // Distinguishing hash should not appear in the signature
        assert_eq!(display, "fn my_function(I32) -> F64");
        assert!(!display.contains("debug_hash_info"));

        // Should still be able to parse it back
        let parsed: SymbolSignature = display.parse().unwrap();
        match parsed {
            SymbolSignature::Function {
                name,
                lazy,
                params,
                results,
            } => {
                assert_eq!(name.name, "my_function");
                // The parsed version won't have the distinguishing hash
                assert_eq!(name.distinguishing_hash, "");
                assert!(!lazy);
                assert_eq!(params, vec![Type::I32]);
                assert_eq!(results, vec![Type::F64]);
            }
            _ => panic!("Expected function signature"),
        }
    }
}
