[package]
name = "wamex_metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcode = { version = "0.6.0" }

nom = { version = "8.0.0", features = ["std"], optional = true }
serde_json = { version = "1.0.104", optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }

rustc-demangle = { version = "0.1.24", optional = true }
wasmparser = { version = "0.238.0", optional = true }

[features]
default = []
serde = ["dep:serde", "dep:serde_json", "dep:nom"]
parser = ["dep:wasmparser", "dep:rustc-demangle"]
# Symbol demangling and conversion from wasmparser types
full = ["parser", "serde"]
